//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Feb 10 15:31:33 2026 by ROOT version 6.36.04)
//      from the StreamerInfo in file /afs/hep.wisc.edu/home/kmartine/Event_Generation/MG5_aMC_v3_6_7/ppToZZ/Events/run_01/tag_1_delphes_events.root
//////////////////////////////////////////////////////////


#ifndef Electron_h
#define Electron_h
class Electron;

#include "Rtypes.h"
#include "SortableObject.h"
#include "TRef.h"

class Electron : public SortableObject {

public:
// Nested classes declaration.

public:
// Data Members.
   float       PT;          //electron transverse momentum
   float       Eta;         //electron pseudorapidity
   float       Phi;         //electron azimuthal angle
   float       T;           //particle arrival time of flight
   int         Charge;      //electron charge
   float       EhadOverEem;    //ratio of the hadronic versus electromagnetic energy deposited in the calorimeter
   TRef        Particle;       //reference to generated particle
   float       IsolationVar;    //isolation variable
   float       IsolationVarRhoCorr;    //isolation variable
   float       SumPtCharged;           //isolation variable
   float       SumPtNeutral;           //isolation variable
   float       SumPtChargedPU;         //isolation variable
   float       SumPt;                  //isolation variable
   float       D0;                     //track transverse impact parameter
   float       DZ;                     //track longitudinal impact parameter
   float       ErrorD0;                //track transverse impact parameter error
   float       ErrorDZ;                //track longitudinal impact parameter error

   Electron();
   Electron(Electron && ) = default;
   Electron &operator=(const Electron & );
   Electron(const Electron & );
   virtual ~Electron();

   ClassDef(Electron,5); // Generated by MakeProject.
};
#endif
