//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Feb 10 15:31:33 2026 by ROOT version 6.36.04)
//      from the StreamerInfo in file /afs/hep.wisc.edu/home/kmartine/Event_Generation/MG5_aMC_v3_6_7/ppToZZ/Events/run_01/tag_1_delphes_events.root
//////////////////////////////////////////////////////////


#ifndef Event_h
#define Event_h
class Event;

#include "Rtypes.h"
#include "TObject.h"

class Event : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   Long64_t    Number;      //event number
   float       ReadTime;    //read time
   float       ProcTime;    //processing time

   Event();
   Event(Event && ) = default;
   Event &operator=(const Event & );
   Event(const Event & );
   virtual ~Event();

   ClassDef(Event,2); // Generated by MakeProject.
};
#endif
