//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Feb 10 15:31:33 2026 by ROOT version 6.36.04)
//      from the StreamerInfo in file /afs/hep.wisc.edu/home/kmartine/Event_Generation/MG5_aMC_v3_6_7/ppToZZ/Events/run_01/tag_1_delphes_events.root
//////////////////////////////////////////////////////////


#ifndef GenParticle_h
#define GenParticle_h
class GenParticle;

#include "Rtypes.h"
#include "SortableObject.h"

class GenParticle : public SortableObject {

public:
// Nested classes declaration.

public:
// Data Members.
   int         PID;         //particle HEP ID number | hepevt.idhep[number]
   int         Status;      //particle status | hepevt.isthep[number]
   int         IsPU;        //0 or 1 for particles from pile-up interactions
   int         M1;          //particle 1st mother | hepevt.jmohep[number][0] - 1
   int         M2;          //particle 2nd mother | hepevt.jmohep[number][1] - 1
   int         D1;          //particle 1st daughter | hepevt.jdahep[number][0] - 1
   int         D2;          //particle last daughter | hepevt.jdahep[number][1] - 1
   int         Charge;      //particle charge
   float       Mass;        //particle mass
   float       E;           //particle energy | hepevt.phep[number][3]
   float       Px;          //particle momentum vector (x component) | hepevt.phep[number][0]
   float       Py;          //particle momentum vector (y component) | hepevt.phep[number][1]
   float       Pz;          //particle momentum vector (z component) | hepevt.phep[number][2]
   float       P;           //particle momentum
   float       PT;          //particle transverse momentum
   float       Eta;         //particle pseudorapidity
   float       Phi;         //particle azimuthal angle
   float       Rapidity;    //particle rapidity
   float       T;           //particle vertex position (t component) | hepevt.vhep[number][3]
   float       X;           //particle vertex position (x component) | hepevt.vhep[number][0]
   float       Y;           //particle vertex position (y component) | hepevt.vhep[number][1]
   float       Z;           //particle vertex position (z component) | hepevt.vhep[number][2]

   GenParticle();
   GenParticle(GenParticle && ) = default;
   GenParticle &operator=(const GenParticle & );
   GenParticle(const GenParticle & );
   virtual ~GenParticle();

   ClassDef(GenParticle,3); // Generated by MakeProject.
};
#endif
