//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Feb 10 15:31:33 2026 by ROOT version 6.36.04)
//      from the StreamerInfo in file /afs/hep.wisc.edu/home/kmartine/Event_Generation/MG5_aMC_v3_6_7/ppToZZ/Events/run_01/tag_1_delphes_events.root
//////////////////////////////////////////////////////////


#ifndef HepMCEvent_h
#define HepMCEvent_h
class HepMCEvent;

#include "Rtypes.h"
#include "Event.h"

class HepMCEvent : public Event {

public:
// Nested classes declaration.

public:
// Data Members.
   int         ProcessID;    //unique signal process id | signal_process_id()
   int         MPI;          //number of multi parton interactions | mpi()
   float       Weight;       //weight for the event
   float       CrossSection;    //cross-section in pb
   float       CrossSectionError;    //cross-section error in pb
   float       Scale;                //energy scale, see hep-ph/0109068 | event_scale()
   float       AlphaQED;             //QED coupling, see hep-ph/0109068 | alphaQED()
   float       AlphaQCD;             //QCD coupling, see hep-ph/0109068 | alphaQCD()
   int         ID1;                  //flavour code of first parton | pdf_info()->id1()
   int         ID2;                  //flavour code of second parton | pdf_info()->id2()
   float       X1;                   //fraction of beam momentum carried by first parton ("beam side") | pdf_info()->x1()
   float       X2;                   //fraction of beam momentum carried by second parton ("target side") | pdf_info()->x2()
   float       ScalePDF;             //Q-scale used in evaluation of PDF's (in GeV) | pdf_info()->scalePDF()
   float       PDF1;                 //PDF (id1, x1, Q) | pdf_info()->pdf1()
   float       PDF2;                 //PDF (id2, x2, Q) | pdf_info()->pdf2()

   HepMCEvent();
   HepMCEvent(HepMCEvent && ) = default;
   HepMCEvent &operator=(const HepMCEvent & );
   HepMCEvent(const HepMCEvent & );
   virtual ~HepMCEvent();

   ClassDef(HepMCEvent,4); // Generated by MakeProject.
};
#endif
