//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Feb 10 15:31:33 2026 by ROOT version 6.36.04)
//      from the StreamerInfo in file /afs/hep.wisc.edu/home/kmartine/Event_Generation/MG5_aMC_v3_6_7/ppToZZ/Events/run_01/tag_1_delphes_events.root
//////////////////////////////////////////////////////////


#ifndef Jet_h
#define Jet_h
class Jet;

#include "Rtypes.h"
#include "SortableObject.h"
#include "TLorentzVector.h"
#include "TRefArray.h"

class Jet : public SortableObject {

public:
// Nested classes declaration.

public:
// Data Members.
   float       PT;          //jet transverse momentum
   float       Eta;         //jet pseudorapidity
   float       Phi;         //jet azimuthal angle
   float       T;           //particle arrival time of flight
   float       Mass;        //jet invariant mass
   float       DeltaEta;    //jet radius in pseudorapidity
   float       DeltaPhi;    //jet radius in azimuthal angle
   unsigned int Flavor;      //jet flavor
   unsigned int FlavorAlgo;    //jet flavor
   unsigned int FlavorPhys;    //jet flavor
   unsigned int TauFlavor;     //jet flavor according to Tau tagging module
   unsigned int BTag;          //0 or 1 for a jet that has been tagged as containing a heavy quark
   unsigned int BTagAlgo;      //0 or 1 for a jet that has been tagged as containing a heavy quark
   unsigned int BTagPhys;      //0 or 1 for a jet that has been tagged as containing a heavy quark
   unsigned int TauTag;        //0 or 1 for a jet that has been tagged as a tau
   float        TauWeight;     //probability for jet to be identified as tau
   int          Charge;        //tau charge
   float        EhadOverEem;    //ratio of the hadronic versus electromagnetic energy deposited in the calorimeter
   int          NCharged;       //number of charged constituents
   int          NNeutrals;      //number of neutral constituents
   float        NeutralEnergyFraction;    //charged energy fraction
   float        ChargedEnergyFraction;    //neutral energy fraction
   float        Beta;                     //(sum pt of charged pile-up constituents)/(sum pt of charged constituents)
   float        BetaStar;                 //(sum pt of charged constituents coming from hard interaction)/(sum pt of charged constituents)
   float        MeanSqDeltaR;             //average distance (squared) between constituent and jet weighted by pt (squared) of constituent
   float        PTD;                      //average pt between constituent and jet weighted by pt of constituent
   float        FracPt[5];                //(sum pt of constituents within a ring 0.1*i < DeltaR < 0.1*(i+1))/(sum pt of constituents)
   float        Tau[5];                   //N-subjettiness
   TLorentzVector SoftDroppedJet;           //
   TLorentzVector SoftDroppedSubJet1;       //
   TLorentzVector SoftDroppedSubJet2;       //
   TLorentzVector TrimmedP4[5];             //first entry (i = 0) is the total Trimmed Jet 4-momenta and from i = 1 to 4 are the trimmed subjets 4-momenta
   TLorentzVector PrunedP4[5];              //first entry (i = 0) is the total Pruned Jet 4-momenta and from i = 1 to 4 are the pruned subjets 4-momenta
   TLorentzVector SoftDroppedP4[5];         //first entry (i = 0) is the total SoftDropped Jet 4-momenta and from i = 1 to 4 are the pruned subjets 4-momenta
   int            NSubJetsTrimmed;          //number of subjets trimmed
   int            NSubJetsPruned;           //number of subjets pruned
   int            NSubJetsSoftDropped;      //number of subjets soft-dropped
   double         ExclYmerge12;             //
   double         ExclYmerge23;             //
   double         ExclYmerge34;             //
   double         ExclYmerge45;             //
   double         ExclYmerge56;             //
   TRefArray      Constituents;             //references to constituents
   TRefArray      Particles;                //references to generated particles
   TLorentzVector Area;                     //

   Jet();
   Jet(Jet && ) = default;
   Jet &operator=(const Jet & );
   Jet(const Jet & );
   virtual ~Jet();

   ClassDef(Jet,6); // Generated by MakeProject.
};
#endif
