//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Feb 10 15:31:33 2026 by ROOT version 6.36.04)
//      from the StreamerInfo in file /afs/hep.wisc.edu/home/kmartine/Event_Generation/MG5_aMC_v3_6_7/ppToZZ/Events/run_01/tag_1_delphes_events.root
//////////////////////////////////////////////////////////


#ifndef MissingET_h
#define MissingET_h
class MissingET;

#include "Rtypes.h"
#include "TObject.h"

class MissingET : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   float       MET;         //mising transverse energy
   float       Eta;         //mising energy pseudorapidity
   float       Phi;         //mising energy azimuthal angle

   MissingET();
   MissingET(MissingET && ) = default;
   MissingET &operator=(const MissingET & );
   MissingET(const MissingET & );
   virtual ~MissingET();

   ClassDef(MissingET,2); // Generated by MakeProject.
};
#endif
