//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Feb 10 15:31:33 2026 by ROOT version 6.36.04)
//      from the StreamerInfo in file /afs/hep.wisc.edu/home/kmartine/Event_Generation/MG5_aMC_v3_6_7/ppToZZ/Events/run_01/tag_1_delphes_events.root
//////////////////////////////////////////////////////////


#ifndef Muon_h
#define Muon_h
class Muon;

#include "Rtypes.h"
#include "SortableObject.h"
#include "TRef.h"

class Muon : public SortableObject {

public:
// Nested classes declaration.

public:
// Data Members.
   float       PT;          //muon transverse momentum
   float       Eta;         //muon pseudorapidity
   float       Phi;         //muon azimuthal angle
   float       T;           //particle arrival time of flight
   int         Charge;      //muon charge
   TRef        Particle;    //reference to generated particle
   float       IsolationVar;    //isolation variable
   float       IsolationVarRhoCorr;    //isolation variable
   float       SumPtCharged;           //isolation variable
   float       SumPtNeutral;           //isolation variable
   float       SumPtChargedPU;         //isolation variable
   float       SumPt;                  //isolation variable
   float       D0;                     //track transverse impact parameter
   float       DZ;                     //track longitudinal impact parameter
   float       ErrorD0;                //track transverse impact parameter error
   float       ErrorDZ;                //track longitudinal impact parameter error

   Muon();
   Muon(Muon && ) = default;
   Muon &operator=(const Muon & );
   Muon(const Muon & );
   virtual ~Muon();

   ClassDef(Muon,5); // Generated by MakeProject.
};
#endif
