//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Feb 10 15:31:33 2026 by ROOT version 6.36.04)
//      from the StreamerInfo in file /afs/hep.wisc.edu/home/kmartine/Event_Generation/MG5_aMC_v3_6_7/ppToZZ/Events/run_01/tag_1_delphes_events.root
//////////////////////////////////////////////////////////


#ifndef Photon_h
#define Photon_h
class Photon;

#include "Rtypes.h"
#include "SortableObject.h"
#include "TRefArray.h"

class Photon : public SortableObject {

public:
// Nested classes declaration.

public:
// Data Members.
   float       PT;          //photon transverse momentum
   float       Eta;         //photon pseudorapidity
   float       Phi;         //photon azimuthal angle
   float       E;           //photon energy
   float       T;           //particle arrival time of flight
   float       EhadOverEem;    //ratio of the hadronic versus electromagnetic energy deposited in the calorimeter
   TRefArray   Particles;      //references to generated particles
   float       IsolationVar;    //isolation variable
   float       IsolationVarRhoCorr;    //isolation variable
   float       SumPtCharged;           //isolation variable
   float       SumPtNeutral;           //isolation variable
   float       SumPtChargedPU;         //isolation variable
   float       SumPt;                  //isolation variable
   int         Status;                 //1: prompt, 2: non prompt, 3: fake

   Photon();
   Photon(Photon && ) = default;
   Photon &operator=(const Photon & );
   Photon(const Photon & );
   virtual ~Photon();

   ClassDef(Photon,5); // Generated by MakeProject.
};
#endif
