//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Feb 10 15:31:33 2026 by ROOT version 6.36.04)
//      from the StreamerInfo in file /afs/hep.wisc.edu/home/kmartine/Event_Generation/MG5_aMC_v3_6_7/ppToZZ/Events/run_01/tag_1_delphes_events.root
//////////////////////////////////////////////////////////


#ifndef ScalarHT_h
#define ScalarHT_h
class ScalarHT;

#include "Rtypes.h"
#include "TObject.h"

class ScalarHT : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   float       HT;          //scalar sum of transverse momenta

   ScalarHT();
   ScalarHT(ScalarHT && ) = default;
   ScalarHT &operator=(const ScalarHT & );
   ScalarHT(const ScalarHT & );
   virtual ~ScalarHT();

   ClassDef(ScalarHT,2); // Generated by MakeProject.
};
#endif
