//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Feb 10 15:31:33 2026 by ROOT version 6.36.04)
//      from the StreamerInfo in file /afs/hep.wisc.edu/home/kmartine/Event_Generation/MG5_aMC_v3_6_7/ppToZZ/Events/run_01/tag_1_delphes_events.root
//////////////////////////////////////////////////////////


#ifndef SortableObject_h
#define SortableObject_h
class SortableObject;

#include "Rtypes.h"
#include "TObject.h"

class SortableObject : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.

   SortableObject();
   SortableObject(SortableObject && ) = default;
   SortableObject &operator=(const SortableObject & );
   SortableObject(const SortableObject & );
   virtual ~SortableObject();

   ClassDef(SortableObject,2); // Generated by MakeProject.
};
#endif
