//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Feb 10 15:31:33 2026 by ROOT version 6.36.04)
//      from the StreamerInfo in file /afs/hep.wisc.edu/home/kmartine/Event_Generation/MG5_aMC_v3_6_7/ppToZZ/Events/run_01/tag_1_delphes_events.root
//////////////////////////////////////////////////////////


#ifndef Tower_h
#define Tower_h
class Tower;

#include "Rtypes.h"
#include "SortableObject.h"
#include "TRefArray.h"

class Tower : public SortableObject {

public:
// Nested classes declaration.

public:
// Data Members.
   float       ET;          //calorimeter tower transverse energy
   float       Eta;         //calorimeter tower pseudorapidity
   float       Phi;         //calorimeter tower azimuthal angle
   float       E;           //calorimeter tower energy
   float       T;           //calo deposit time, averaged by sqrt(EM energy) over all particles
   float       X;           //calo tower position
   float       Y;           //calo tower position
   float       Z;           //calo tower position
   int         NTimeHits;    //number of hits contributing to time measurement
   float       Eem;          //calorimeter tower electromagnetic energy
   float       Ehad;         //calorimeter tower hadronic energy
   float       Etrk;         //total charged energy hitting tower
   float       Edges[4];     //calorimeter tower edges
   int         IsPU;         //0 or 1 for particles from pile-up interactions
   int         IsRecoPU;     //0 or 1 for reconstructed particles from pile-up
   float       HardEnergyFraction;    //fraction of hard scattering vs PU energy
   TRefArray   Particles;             //references to generated particles

   Tower();
   Tower(Tower && ) = default;
   Tower &operator=(const Tower & );
   Tower(const Tower & );
   virtual ~Tower();

   ClassDef(Tower,6); // Generated by MakeProject.
};
#endif
