//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Feb 10 15:31:33 2026 by ROOT version 6.36.04)
//      from the StreamerInfo in file /afs/hep.wisc.edu/home/kmartine/Event_Generation/MG5_aMC_v3_6_7/ppToZZ/Events/run_01/tag_1_delphes_events.root
//////////////////////////////////////////////////////////


#ifndef Track_h
#define Track_h
class Track;

#include "Rtypes.h"
#include "SortableObject.h"
#include "TRef.h"

class Track : public SortableObject {

public:
// Nested classes declaration.

public:
// Data Members.
   int         PID;         //HEP ID number
   int         Charge;      //track charge
   int         IsPU;        //0 or 1 for particles from pile-up interactions
   int         IsRecoPU;    //0 or 1 for reconstructed particles from pile-up
   float       HardEnergyFraction;    //fraction of hard scattering vs PU energy in the particle flow candidate
   float       P;                     //track momentum
   float       PT;                    //track transverse momentum
   float       Eta;                   //track pseudorapidity
   float       Phi;                   //track azimuthal angle
   float       CtgTheta;              //track cotangent of theta
   float       C;                     //track curvature inverse
   float       Mass;                  //particle mass
   float       EtaOuter;              //track pseudorapidity at the tracker edge
   float       PhiOuter;              //track azimuthal angle at the tracker edge
   float       T;                     //track vertex position (t component)
   float       X;                     //track vertex position (x component)
   float       Y;                     //track vertex position (y component)
   float       Z;                     //track vertex position (z component)
   float       TOuter;                //track position (t component) at the tracker edge
   float       XOuter;                //track position (x component) at the tracker edge
   float       YOuter;                //track position (y component) at the tracker edge
   float       ZOuter;                //track position (z component) at the tracker edge
   float       Xd;                    //X coordinate of point of closest approach to vertex
   float       Yd;                    //Y coordinate of point of closest approach to vertex
   float       Zd;                    //Z coordinate of point of closest approach to vertex
   float       XFirstHit;             //X coordinate of point of closest approach to vertex
   float       YFirstHit;             //Y coordinate of point of closest approach to vertex
   float       ZFirstHit;             //Z coordinate of point of closest approach to vertex
   float       L;                     //track path length
   float       D0;                    //track transverse impact parameter
   float       DZ;                    //track longitudinal impact parameter
   float       Nclusters;             //Number of ionization clusters
   float       dNdx;                  //Number of ionization clusters
   float       ErrorP;                //track momentum error
   float       ErrorPT;               //track transverse momentum error
   float       ErrorPhi;              //track azimuthal angle error
   float       ErrorCtgTheta;         //track cotangent of theta error
   float       ErrorT;                //time measurement error
   float       ErrorD0;               //track transverse impact parameter error
   float       ErrorDZ;               //track longitudinal impact parameter error
   float       ErrorC;                //track curvature error
   float       ErrorD0Phi;            //
   float       ErrorD0C;              //
   float       ErrorD0DZ;             //
   float       ErrorD0CtgTheta;       //
   float       ErrorPhiC;             //
   float       ErrorPhiDZ;            //
   float       ErrorPhiCtgTheta;      //
   float       ErrorCDZ;              //
   float       ErrorCCtgTheta;        //
   float       ErrorDZCtgTheta;       //
   TRef        Particle;              //reference to generated particle
   int         VertexIndex;           //reference to vertex

   Track();
   Track(Track && ) = default;
   Track &operator=(const Track & );
   Track(const Track & );
   virtual ~Track();

   ClassDef(Track,5); // Generated by MakeProject.
};
#endif
