//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Feb 10 15:31:33 2026 by ROOT version 6.36.04)
//      from the StreamerInfo in file /afs/hep.wisc.edu/home/kmartine/Event_Generation/MG5_aMC_v3_6_7/ppToZZ/Events/run_01/tag_1_delphes_events.root
//////////////////////////////////////////////////////////


#ifndef Weight_h
#define Weight_h
class Weight;

#include "Rtypes.h"
#include "TObject.h"

class Weight : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   float       Weight;      //weight for the event

   Weight();
   Weight(Weight && ) = default;
   Weight &operator=(const Weight & );
   Weight(const Weight & );
   virtual ~Weight();

   ClassDef(Weight,2); // Generated by MakeProject.
};
#endif
